### ISSUE TITLE
All versions of CKAN give errors saying The remote server returned an error (401) Unauthorized

### ISSUE THREAD

**Issue by AlonmifexMaximus** [KSP-CKAN/CKAN-GUI#74] opened 2015-04-27 01:46 UTC
How do I fix this?

**Comment by Dazpoet** [comment] 2015-04-27 08:18
Update to the latest version 1.6.11, which resolves this issue. Also this is a duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/113 which has been resolved and closed so I'm closing this aswell.

**Closed by Dazpoet** 2015-04-27 08:18 UTC
